I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 162, in script
    maid talking "Nabe, at your service."
Exception: Say has image attributes (u'talking',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 162, in script
    maid talking "Nabe, at your service."
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\character.py", line 1073, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\character.py", line 942, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\character.py", line 868, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes (u'talking',), but there's no image tag associated with the speaking character.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
cct382_vn 1.0
Mon Nov 30 00:43:01 2020
